# Generated by Django 5.2.5 on 2025-08-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_panel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
