# Generated by Django 5.2.5 on 2025-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_panel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
