# Generated by Django 5.2.5 on 2025-08-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='image',
            field=models.ImageField(upload_to='panels'),
        ),
    ]
