# Generated by Django 5.2.5 on 2025-08-14 18:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_panel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
