# Generated by Django 5.2.5 on 2025-08-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_panel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.category'),
        ),
    ]
