# Generated by Django 5.2.5 on 2025-08-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_panel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='category',
        ),
        migrations.AddField(
            model_name='panel',
            name='categories',
            field=models.ManyToManyField(to='panel.category'),
        ),
    ]
